services:
  - type: web
    name: trianime
    runtime: docker

    plan: free
    region: oregon

    dockerfilePath: ./Dockerfile
    dockerContext: .

    healthCheckPath: /

    autoDeployTrigger: commit

    envVars:
      - key: PORT
        value: "10000"
